import { Box, SimpleGrid, Center } from "@chakra-ui/react";
import { getEvents } from "@/modules/event/api";
import { GetDiceEventsResponse } from "@/modules/event/types";
import { useInfiniteQuery } from "@tanstack/react-query";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import EventCard from "@/modules/event/EventCard";

interface EventListHomeProps {
  events: GetDiceEventsResponse;
}
const EventListHome: NextPage<EventListHomeProps> = (props) => {
  const [searchTerms, setSearchTerms] = useState("");
  const { data, error, fetchNextPage, hasNextPage, isFetching, isFetchingNextPage, status } =
    useInfiniteQuery(["events", { searchTerms }], ({ pageParam = 1 }) =>
      getEvents({ filter: { venue: searchTerms }, page: { number: pageParam } })
    );

  return (
    <Center>
      <Head>
        <title>DICE Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SimpleGrid columns={{ base: 1, md: 2, lg: 3, "2xl": 4 }} spacingX={8}>
        {data?.pages.map((response) => {
          return response.data.map((event) => {
            return (
              <EventCard
                key={event.id}
                saleStartDate={event.sale_start_date}
                eventImages={event.event_images}
                date={event.date}
                name={event.name}
                location={event.location}
                description={event.description}
                lineup={event.lineup}
                ticketTypes={event.ticket_types}
                currency={event.currency}
                isFeatured={event.featured}
                venue={event.venue}
              />
            );
          });
        })}
      </SimpleGrid>
    </Center>
  );
};

export default EventListHome;
